name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Update Capacitor packages
        run: |
          npm install @capacitor/core@latest @capacitor/cli@latest
          npm install @capacitor/ios

      - name: Build web app
        run: npm run build

      - name: Add iOS platform
        run: npx cap add ios

      - name: Copy web build to iOS
        run: npx cap copy ios

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod repo update
          pod install --repo-update

      - name: Build iOS app (archive, unsigned)
        run: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            clean archive \
            -archivePath $PWD/build/App.xcarchive

      - name: Export .ipa (unsigned)
        run: |
          cd ios
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>development</string></dict></plist>')
          ls -l build/ipa

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/ipa
