name: Build iOS App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node Dependencies
        run: |
          npm install
          npm install @capacitor/ios
          # npm install --legacy-peer-deps 
          
      - name: Build web app
        run: npm run build
      - name: Prepare Capacitor iOS Project
        run: |
          npx cap add ios
          npx cap copy ios
      - name: Install CocoaPods and Update Dependencies
        working-directory: ./ios/App
        run: |
          sudo gem install cocoapods 
          pod install
      - name: Build iOS app (archive, unsigned)
        working-directory: ./ios/App
        run: |
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            clean archive \
            -archivePath $PWD/build/App.xcarchive
      - name: Create IPA from Archive
        working-directory: ./ios/App
        run: |
          mkdir -p build/ipa/Payload
          cp -r build/App.xcarchive/Products/Applications/App.app build/ipa/Payload/
          cd build/ipa
          zip -r App.ipa Payload
          rm -rf Payload
          ls -lh
      - name: Upload.ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/App/build/ipa/App.ipa
