name: Build iOS Apps (Unsigned IPA)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Update Capacitor packages
        run: |
          npm install @capacitor/core@latest @capacitor/cli@latest
          npm install @capacitor/ios

      - name: Build web app
        run: npm run build

      - name: Add iOS platform (ensure latest)
        run: npx cap add ios || echo "iOS platform already added"

      - name: Copy web build to iOS
        run: npx cap copy ios

      - name: Build iOS app (unsigned)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            clean archive \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: Export unsigned .ipa
        run: |
          cd ios/App
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>development</string><key>signingStyle</key><string>manual</string></dict></plist>')
          ls -l build/ipa

      - name: Upload unsigned .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: ios/App/build/ipa
